package com.senamed.backend.appointment;

import com.senamed.backend.catalog.ServiceOffering;
import com.senamed.backend.clinic.Clinic;
import com.senamed.backend.doctor.Doctor;
import com.senamed.backend.patient.Patient;
import com.senamed.backend.tenant.TenantScopedEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A patient-booked appointment, created through the public (unauthenticated) scheduling flow -
 * see {@code com.senamed.backend.appointment.publicapi.PublicSchedulingService}.
 *
 * <p><strong>Critical security note:</strong> every endpoint that creates/reads this entity is
 * public (no JWT), so {@link com.senamed.backend.tenant.TenantFilterInterceptor} never enables the
 * Hibernate tenant filter for these requests (it only does so when
 * {@link com.senamed.backend.tenant.TenantContext#isAuthenticated()} is true). This makes the
 * {@code @Filter} inherited from {@link TenantScopedEntity} a no-op safety net here, not a real
 * protection - every query touching appointments (and the doctor/availability/time-off data used
 * to compute slots) MUST explicitly scope by {@code clinicId} or by an already clinic-validated
 * {@code doctorId}, never rely on the filter alone.</p>
 *
 * <p>Mirrors {@link Doctor}'s pattern for the inherited (read-only) {@code clinicId} column: the
 * actual FK is written through the {@link #clinic} association, which is derived from
 * {@code doctor.getClinic()} at construction time so callers only ever need to pass a
 * {@link Doctor}.</p>
 */
@Entity
@Table(name = "appointments")
public class Appointment extends TenantScopedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "clinic_id", nullable = false, updatable = false)
    private Clinic clinic;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id", nullable = false, updatable = false)
    private Doctor doctor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = true, updatable = false)
    private Patient patient;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "service_id", nullable = true, updatable = false)
    private ServiceOffering service;

    @Column(nullable = true)
    private BigDecimal price;

    @Column(name = "patient_name", nullable = false)
    private String patientName;

    @Column(name = "patient_email", nullable = false)
    private String patientEmail;

    @Column(name = "patient_phone")
    private String patientPhone;

    @Column(name = "starts_at", nullable = false)
    private LocalDateTime startsAt;

    @Column(name = "ends_at", nullable = false)
    private LocalDateTime endsAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AppointmentStatus status = AppointmentStatus.CONFIRMED;

    @Column(name = "lgpd_consent_at", nullable = false, updatable = false)
    private Instant lgpdConsentAt;

    /**
     * Generated by Postgres itself ({@code DEFAULT gen_random_uuid()}, see the V3 migration)
     * rather than in Java - {@code @Generated(event = EventType.INSERT)} tells Hibernate to SELECT
     * the column back right after the INSERT so {@link #getCancelToken()} is populated on the
     * managed entity returned by {@code save}.
     */
    @Generated(event = EventType.INSERT)
    @Column(name = "cancel_token", insertable = false, updatable = false, nullable = false)
    private UUID cancelToken;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    @Column(name = "confirmed_at")
    private Instant confirmedAt;

    protected Appointment() {
        // JPA
    }

    public Appointment(
            Doctor doctor,
            String patientName,
            String patientEmail,
            String patientPhone,
            LocalDateTime startsAt,
            LocalDateTime endsAt,
            Instant lgpdConsentAt) {
        this(doctor, null, patientName, patientEmail, patientPhone, startsAt, endsAt, lgpdConsentAt);
    }

    public Appointment(
            Doctor doctor,
            Patient patient,
            String patientName,
            String patientEmail,
            String patientPhone,
            LocalDateTime startsAt,
            LocalDateTime endsAt,
            Instant lgpdConsentAt) {
        this(doctor, patient, null, patientName, patientEmail, patientPhone, startsAt, endsAt, lgpdConsentAt);
    }

    public Appointment(
            Doctor doctor,
            Patient patient,
            ServiceOffering service,
            String patientName,
            String patientEmail,
            String patientPhone,
            LocalDateTime startsAt,
            LocalDateTime endsAt,
            Instant lgpdConsentAt) {
        this.doctor = doctor;
        this.clinic = doctor.getClinic();
        this.patient = patient;
        this.service = service;
        this.price = service != null ? service.getPrice() : null;
        this.patientName = patientName;
        this.patientEmail = patientEmail;
        this.patientPhone = patientPhone;
        this.startsAt = startsAt;
        this.endsAt = endsAt;
        this.lgpdConsentAt = lgpdConsentAt;
    }

    public Long getId() {
        return id;
    }

    public Clinic getClinic() {
        return clinic;
    }

    public Doctor getDoctor() {
        return doctor;
    }

    public Patient getPatient() {
        return patient;
    }

    public ServiceOffering getService() {
        return service;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public String getPatientName() {
        return patientName;
    }

    public String getPatientEmail() {
        return patientEmail;
    }

    public String getPatientPhone() {
        return patientPhone;
    }

    public LocalDateTime getStartsAt() {
        return startsAt;
    }

    public LocalDateTime getEndsAt() {
        return endsAt;
    }

    public AppointmentStatus getStatus() {
        return status;
    }

    public Instant getLgpdConsentAt() {
        return lgpdConsentAt;
    }

    public UUID getCancelToken() {
        return cancelToken;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getConfirmedAt() {
        return confirmedAt;
    }

    public void cancel() {
        this.status = AppointmentStatus.CANCELLED;
    }

    public void markAttended() {
        this.status = AppointmentStatus.ATTENDED;
    }

    /** Staff-initiated reschedule from the dashboard (KAN-97) - changes the slot, keeps the doctor/patient. */
    public void reschedule(LocalDateTime startsAt, LocalDateTime endsAt) {
        this.startsAt = startsAt;
        this.endsAt = endsAt;
    }

    /** Records the patient's attendance confirmation (RF-016) - orthogonal to {@link #status}. */
    public void confirm() {
        this.confirmedAt = Instant.now();
    }
}
